name: Package and push to registry repo
on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile --root . --font-path ./fonts ./template/resume.typ resume.pdf
      - name: Push to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "[bot]: generate pdf" && git push
